version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LOG_RETENTION_MS: 5000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  test:
    build: .
    depends_on:
      - kafka
      - zookeeper
    environment:
      - CXX